### ISSUE TITLE
Ensure all CSV export views are exporting all data

### ISSUE THREAD

**Issue by ramereth** [osuosl/streamwebs#519] opened 2017-10-30 23:58 UTC
I noticed while working on another issue that the CSV export views didn't include some of the changes from #509. This made me wonder if we should go through and verify that all of the recent changes to the various views have also been carried to the export views properly.

**Comment by hertelc** [comment] 2017-11-14 00:15
Found that exporting Water Quality includes more data than the site selected.  See attached export from "Wenaha River"   http://streamwebs.org/sites/wenaha-river/#3
[WenahaRiver_Export_LiveSite.xlsx](https://github.com/osuosl/streamwebs/files/1469093/WenahaRiver_Export_LiveSite.xlsx)

**Comment by CarvellWakeman** [comment] 2017-12-30 01:39
I'm not sure if my understanding of this bug is correct. Does this sound right?

Let there be an example site _creek_, which has 40 data sheets from 12 different schools.
Let there be 4 water quality sheets from school _A_
Let there be 3 water quality sheets from school _B_
Let there be 10 macroinvertebrate sheets from school _C_ (and no other macro sheets at all)

When exporting water quality data, you expect 7 rows, 4 coming from school A, and 3 coming from school B? But currently there are less than 7 rows in the exported data sheet?

**Comment by hertelc** [comment] 2017-12-30 01:41
Have you tried doing a few exports for Water Quality?  What I was seeing lately was data for multiple sites in the same sheet.

On Dec 29, 2017 5:39 PM, Zach Lerew <notifications@github.com> wrote:

I'm not sure if my understanding of this bug is correct. Does this sound right?

Let there be an example site creek, which has 40 data sheets from 12 different schools.
Let there be 4 water quality sheets from school A
Let there be 3 water quality sheets from school B
Let there be 10 macroinvertebrate sheets from school C (and no other macro sheets at all)

When exporting water quality data, you expect 7 rows, 4 coming from school A, and 3 coming from school B? But currently there are less than 7 rows in the exported data sheet?

**Comment by hertelc** [comment] 2017-12-30 01:43
Also there have been several issues with the exports so really just need to open them all and make sure they are fully populating.  At one point, yes not all data was included in the exports.

On Dec 29, 2017 5:39 PM, Zach Lerew <notifications@github.com> wrote:

I'm not sure if my understanding of this bug is correct. Does this sound right?

Let there be an example site creek, which has 40 data sheets from 12 different schools.
Let there be 4 water quality sheets from school A
Let there be 3 water quality sheets from school B
Let there be 10 macroinvertebrate sheets from school C (and no other macro sheets at all)

When exporting water quality data, you expect 7 rows, 4 coming from school A, and 3 coming from school B? But currently there are less than 7 rows in the exported data sheet?

**Comment by CarvellWakeman** [comment] 2018-01-02 22:06
@hertelc I was not able to get data from multiple sites on any of the CSV exports. Still have to check and make sure that all expected data is in the export though.

**Comment by hertelc** [comment] 2018-01-03 23:59
I just added a test site on production and a water quality datasheet.  I then did an export and its still huge.  The site is named "Delete Me - Test Site"  I am deleting this site, but what is interesting is if you export the water quality data from the Wenaha River site, my Delete test site is at the bottom of the list...  It almost looks like data as of a certain time is what is populating in this export.  Since September 2017.

[WaterQualityExport_DeleteMe.xlsx](https://github.com/osuosl/streamwebs/files/1602071/WaterQualityExport_DeleteMe.xlsx)
[WaterQualityExport_Wenaha.xlsx](https://github.com/osuosl/streamwebs/files/1602072/WaterQualityExport_Wenaha.xlsx)

**Comment by NathanTan** [comment] 2018-01-11 19:50
Data sheet exports that are fixed

- [X] Water Quality

- [ ] Macro-invertebrates

- [ ] Riparian transect

- [ ] Canopy Cover Survey

- [ ] New Camera Point

- [ ] Soil Survery

- [ ] Riparian Aquatic Survey

**Comment by hertelc** [comment] 2018-02-19 21:23
This looks good in staging.  Closing issue.

**Closed by hertelc** 2018-02-19 21:23 UTC
Labels: Ready for Review, medium priority

**Comment by hertelc** [comment] 2018-05-16 18:46
Tested on staging with Chrome.  Water Quality is exporting too much information again.  Reopening.  

https://streamwebs-staging.osuosl.org/sites/wenaha-river/

**Comment by JerryPeng0112** [comment] 2018-06-20 19:16
The bug is caused by different key used for relation between "water_quality_sample" and "water_quality" data during export.
