### ISSUE TITLE
Mac Safari & Chromebook: Unable to save changes to an account without changing user's email

### ISSUE THREAD

**Issue by gilbertt** [osuosl/streamwebs#612] opened 2018-01-02 23:36 UTC
When editing an existing user, changes to the user cannot be saved if the user's email has not been changed. Clicking the save button results in an error message: "Email: A user with that email address already exists"

**Comment by hertelc** [comment] 2018-01-02 23:53
Also seen on iPad

**Comment by gilbertt** [comment] 2018-01-03 00:14
Same bug applies to contributor accounts. Changes can be saved if the email is removed entirely, then the email can be re-added once it's removed.

**Comment by CarvellWakeman** [comment] 2018-01-03 00:16
Got a fix for it now, on BugFix_Jan2017. I was using form validation to enforce the email field being unique. It's going to require a big migration and will be a pain later because for some reason emails were never unique before this point.

**Comment by hertelc** [comment] 2018-01-03 17:32
Fix looks good to me.

**Comment by hertelc** [comment] 2018-01-03 17:58
Tyler also confirmed.  Closing issue.

**Closed by hertelc** 2018-01-03 17:58 UTC
Labels: bug, high priority, Ready for Review
